### ISSUE TITLE
support multi-dimensional arrays

### ISSUE THREAD

**Issue by chansonZ** [lgarrison/parallel-numpy-rng#4]
Could you support multi-dimensional arrays?
Thanks!

```
parallel_rng.random(size=((100000, 100000)), dtype=np.float32, nthread=12)

site-packages/parallel_numpy_rng/parallel_numpy_rng.py", line 76, in random
    if nthread > size:
TypeError: '>' not supported between instances of 'int' and 'tuple'
```

**Comment by lgarrison** [comment]
Sure, this wouldn't be hard. The workaround in the meantime is quite simple though:
```python
parallel_rng.random(size=100000*100000).reshape(100000, 100000)
```

Really, the only thing required to add built-in support for this is to convert the input size to an `ndarray`, generate `size.prod()` elements, then reshape to the original size. A PR would be welcome!
